### ISSUE TITLE
889 Tool | NASA Recognition

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/889-tool#123]
NASA, as the original creator of the 889 tool, needs to be given more credit on the 889 tool.

https://889.smartpay.gsa.gov/#/

Acceptance Criteria:
- [ ] Implement design changes in footers to match [design](https://user-images.githubusercontent.com/18366192/257282577-8b2f8d12-4d28-4922-ad30-710e9c9f5e8e.png).
  - - [ ] 1st sentence in grey footer.
  - - [ ] Adding attribution & NASA logo in black footer.
- [ ] Add period to the end of the second line in the grey footer: 
"We encourage input! Please provide feedback and suggestions to [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov). "

**Comment by JessicaMarine1** [comment]
@rebekahperillo I believe the scope of this story has changed over time. As a result, I would recommend updating the AC to:

- [ ] Implement design changes in footers to match [design](https://user-images.githubusercontent.com/18366192/257282577-8b2f8d12-4d28-4922-ad30-710e9c9f5e8e.png)
   - [ ] 1st sentence in grey footer
   - [ ] Adding attribution & NASA logo in black footer.
- [ ] Add period to the end of the second line in the grey footer: We encourage input! Please provide feedback and suggestions to [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov).

**Comment by CodyHinze** [comment]
AC has been updated based on @JessicaMarine1's comment above.

Need to get a final version the NASA logo.

**Comment by CodyHinze** [comment]
NOTE: Because this has an image, we will also need to include an Alt tag on the image that describes the NASA logo.

**Comment by rebekahperillo** [comment]
@CodyHinze Found the NASA logo! :) If you need anything else, please let me know. Thank you! 

![Image](https://github.com/GSA/889-tool/assets/133424018/b0e7ea92-0b41-42de-ba57-dfc3773afeb8)

**Comment by CodyHinze** [comment]
The logo above includes the checkerboard background in the image file.  Visually, this is identical to the publicly available version on Wikipedia, but we wanted to ensure we are using the correct version.  and the version used in the nasa.gov website footer.

SVG - https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg

Official SVG - https://www.nasa.gov/wp-content/themes/nasa/assets/images/nasa-logo.svg

I would recommend we use the version that is currently used on the official nasa.gov site.

**Comment by rebekahperillo** [comment]
@klohman Hello again! Do you happen to remember which logo file you used when you created the mockup above? Thank you for your help!

**Comment by klohman** [comment]
> @klohman Hello again! Do you happen to remember which logo file you used when you created the mockup above? Thank you for your help!

@rebekahperillo Looks like I saved the original file to my old Macbook. I agree with @CodyHinze though that we should use the version from the official NASA site if that's available for you to pull.

**Comment by rebekahperillo** [comment]
@klohman Perfect, thank you! 

@CodyHinze Please see Kristen's advice. If you have any questions, please let me know.

**Comment by JennaySDavis** [comment]
**#123 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
|  |Implement design changes in footers to match [design](https://user-images.githubusercontent.com/18366192/257282577-8b2f8d12-4d28-4922-ad30-710e9c9f5e8e.png)|
 |||1st sentence in grey footer|
 |||Adding attribution & NASA logo in black footer|
 |||Add period to the end of the second line in the grey footer:
"We encourage input! Please provide feedback and suggestions to [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov). "|




**Comments/Additional Notes**
N/A


**ADA Compliance (Automated scan via Chrome Lighthouse)**

| Criteria | Score |
| --- | --- | 
| Performance |  |
| Accessibility |  |
| Best Practices |  |

**Comment by johnbeallgsa** [comment]
@JennaySDavis Let's chat about this Monday. I have a few questions on the Performance. Would you happen to know what the score was before? How can the score be improved now, or does that require a new story? Can the improvement be done before releasing it into production?

The NASA logo and everything else look great, though!

**Comment by CodyHinze** [comment]
The current production version of the 889 tools home page (https://889.smartpay.gsa.gov/#/) receives the following in Lighthouse.


Criteria | Score
-- | --
Performance | 97
Accessibility | 100
Best Practices | 91

The performance number on the staging environment should only be used as a guide, it may return a false indicator of server performance and load times that are not reflected on production.

Since the changes made in this ticket only include minor changes in the HTML structure in the footer and the addition of a single optimized SVG image I believe the performance numbers on staging are not a concern.

Please note that there are usability concerns on the Search results screens including the following:

- Responsive layout: The content may overflow the horizontal container in the list.
- Download PDF buttons are not uniquely labeled. All are just labeled as "Download PDF". The aria-labelled-by tag is used incorrectly, that tag accepts an "ID" and not a string.  This is invalid: `aria-labelledby="Download PDF for EXAMPLE BUSINESS NAME LLC"`. Switching to: `**aria-label**="Download PDF for EXAMPLE BUSINESS NAME LLC"` would fix this issue. Aditionally using spaces in IDs in HTML is not allowed.  That is the origin of this issue.  The SVG element in the DOM includes a TITLE element with an ID of "Download PDF for EXAMPLE BUSINESS NAME LLC" that is not allowed since it has spaces and then prevents screen readers from getting the unique content beyond. "Download PDF"
- Unavailable PDF's include disabled buttons that are typically skipped by screen readers
- Pagination at the bottom of the page is incorrectly configured and includes labels that contain code such as `aria-label="Page {{page}}"`
- The icons such as the "Green-Check" and "Warning-Icon" include IDs that are not unique.

**Comment by johnbeallgsa** [comment]
Moving to Done with new enhancement ticket made #146 for a future sprint. 
Excellent work, team, and thank you for all the explanations.
